# Generated by Django 3.1.1 on 2020-09-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('faq_title', models.TextField()),
                ('faq_content', models.TextField()),
                ('faq_order', models.IntegerField()),
                ('faq_datetime', models.DateTimeField(verbose_name='date published')),
                ('mem_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NOTIFICATION',
            fields=[
                ('not_id', models.AutoField(primary_key=True, serialize=False)),
                ('mem_it', models.IntegerField()),
                ('target_mem_id', models.IntegerField()),
                ('not_type', models.CharField(max_length=50)),
                ('not_Content_id', models.IntegerField()),
                ('not_message', models.CharField(max_length=50)),
                ('not_url', models.CharField(max_length=50)),
                ('not_datetime', models.DateTimeField(verbose_name='date published')),
                ('not_read_datetime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='PAYMENT',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_pg', models.CharField(max_length=50)),
                ('pay_type', models.CharField(max_length=50)),
                ('pay_data', models.TextField()),
                ('pay_datetime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='REQUEST',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('user_nickname', models.CharField(max_length=50)),
                ('user_realname', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=50)),
                ('req_total_money', models.IntegerField()),
                ('pay_id', models.CharField(max_length=50)),
                ('pay_pg', models.CharField(max_length=50)),
                ('pay_datetime', models.DateTimeField(verbose_name='date published')),
                ('req_datetime', models.DateTimeField(verbose_name='date published')),
                ('req_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='REVIEW',
            fields=[
                ('rev_id', models.AutoField(primary_key=True, serialize=False)),
                ('bg_id', models.IntegerField()),
                ('rev_title', models.CharField(max_length=50)),
                ('rev_content', models.TextField()),
                ('mem_id', models.IntegerField()),
                ('rev_star', models.IntegerField()),
                ('rev_datetime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('rev_star', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CHAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.IntegerField()),
                ('user_user_id', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('context', models.TextField()),
                ('bg_requset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bg_app.bg_item')),
            ],
        ),
    ]
