# Generated by Django 3.1.1 on 2020-09-18 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BG_CATEGORY',
            fields=[
                ('ca_id', models.AutoField(primary_key=True, serialize=False)),
                ('ca_postkey', models.IntegerField()),
                ('ca_key', models.CharField(max_length=50)),
                ('ca_value', models.CharField(max_length=50)),
                ('ca_parent', models.CharField(max_length=50)),
                ('bca_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BG_COMMENT',
            fields=[
                ('bg_id', models.AutoField(primary_key=True, serialize=False)),
                ('bg_comment_id', models.CharField(max_length=50)),
                ('bg_comment_datetime', models.DateTimeField(verbose_name='date published')),
                ('bg_comment_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BJ_COMMENT',
            fields=[
                ('bj_id', models.AutoField(primary_key=True, serialize=False)),
                ('bj_comment_id', models.CharField(max_length=50)),
                ('bj_comment_datetime', models.DateTimeField(verbose_name='date published')),
                ('bj_comment_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CHAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.IntegerField()),
                ('user_user_id', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('context', models.TextField()),
                ('bg_requset', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('faq_id', models.AutoField(primary_key=True, serialize=False)),
                ('faq_title', models.TextField()),
                ('faq_content', models.TextField()),
                ('faq_order', models.IntegerField()),
                ('faq_datetime', models.DateTimeField(verbose_name='date published')),
                ('mem_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NOTIFICATION',
            fields=[
                ('not_id', models.AutoField(primary_key=True, serialize=False)),
                ('mem_it', models.IntegerField()),
                ('target_mem_id', models.IntegerField()),
                ('not_type', models.CharField(max_length=50)),
                ('not_Content_id', models.IntegerField()),
                ('not_message', models.CharField(max_length=50)),
                ('not_url', models.CharField(max_length=50)),
                ('not_datetime', models.DateTimeField(verbose_name='date published')),
                ('not_read_datetime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='PAYMENT',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_pg', models.CharField(max_length=50)),
                ('pay_type', models.CharField(max_length=50)),
                ('pay_data', models.TextField()),
                ('pay_datetime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='REQUEST',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('user_nickname', models.CharField(max_length=50)),
                ('user_realname', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=50)),
                ('req_total_money', models.IntegerField()),
                ('pay_id', models.CharField(max_length=50)),
                ('pay_pg', models.CharField(max_length=50)),
                ('pay_datetime', models.DateTimeField(verbose_name='date published')),
                ('req_datetime', models.DateTimeField(verbose_name='date published')),
                ('req_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='REVIEW',
            fields=[
                ('rev_id', models.AutoField(primary_key=True, serialize=False)),
                ('bg_id', models.IntegerField()),
                ('rev_title', models.CharField(max_length=50)),
                ('rev_content', models.TextField()),
                ('mem_id', models.IntegerField()),
                ('rev_star', models.IntegerField()),
                ('rev_datetime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='USER',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_nickname', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('ca_key', models.CharField(max_length=50)),
                ('pay_id', models.CharField(max_length=50)),
                ('rev_star', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BJ_POST',
            fields=[
                ('bj_id', models.AutoField(primary_key=True, serialize=False)),
                ('bj_datetime', models.DateTimeField(verbose_name='date published')),
                ('bj_title', models.CharField(max_length=50)),
                ('bj_content', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilyeoapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='BJ_ITEMS',
            fields=[
                ('bj_price', models.IntegerField()),
                ('bj_term', models.DateTimeField(verbose_name='date published')),
                ('bj_content', models.TextField()),
                ('bj_count', models.AutoField(primary_key=True, serialize=False)),
                ('bj_items_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilyeoapp.bj_comment')),
            ],
        ),
        migrations.CreateModel(
            name='BG_POST',
            fields=[
                ('bg_id', models.AutoField(primary_key=True, serialize=False)),
                ('bg_datetime', models.DateTimeField(verbose_name='date published')),
                ('bg_title', models.CharField(max_length=50)),
                ('bg_content', models.TextField()),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilyeoapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='BG_ITEMS',
            fields=[
                ('bg_price', models.IntegerField()),
                ('bg_term', models.DateTimeField(verbose_name='date published')),
                ('bg_content', models.TextField()),
                ('bg_count', models.AutoField(primary_key=True, serialize=False)),
                ('ca_key', models.IntegerField()),
                ('bg_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilyeoapp.bg_post')),
                ('bg_items_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilyeoapp.bg_comment')),
                ('bg_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilyeoapp.chat')),
            ],
        ),
    ]
