# Generated by Django 3.0.6 on 2020-09-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilyeoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='bg_requset',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='NOTIFICATION',
        ),
        migrations.DeleteModel(
            name='PAYMENT',
        ),
        migrations.DeleteModel(
            name='REQUEST',
        ),
        migrations.DeleteModel(
            name='REVIEW',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rev_star',
        ),
        migrations.DeleteModel(
            name='CHAT',
        ),
    ]
