# Generated by Django 3.1.1 on 2020-09-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BG_BOARD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BG_CATEGORY',
            fields=[
                ('ca_id', models.AutoField(primary_key=True, serialize=False)),
                ('ca_postkey', models.IntegerField()),
                ('ca_key', models.CharField(max_length=50)),
                ('ca_value', models.CharField(max_length=50)),
                ('ca_parent', models.CharField(max_length=50)),
                ('bca_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BG_COMMENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_comment_datetime', models.DateTimeField(verbose_name='date published')),
                ('bg_comment_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BG_ITEM',
            fields=[
                ('bg_id', models.AutoField(primary_key=True, serialize=False)),
                ('bg_title', models.CharField(max_length=50)),
                ('bg_content', models.TextField()),
                ('bg_rentalFee', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('bg_startRentalDate', models.DateField()),
                ('bg_endRentalDate', models.DateField()),
                ('bg_reportingTime', models.DateField()),
                ('bg_request', models.BooleanField()),
                ('bg_views', models.IntegerField()),
            ],
        ),
    ]
