# Generated by Django 3.1 on 2020-09-25 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BG_CATEGORY',
            fields=[
                ('ca_id', models.AutoField(primary_key=True, serialize=False)),
                ('ca_postkey', models.IntegerField()),
                ('ca_key', models.CharField(max_length=50)),
                ('ca_value', models.CharField(max_length=50)),
                ('ca_parent', models.CharField(max_length=50)),
                ('bca_order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BG_ITEM',
            fields=[
                ('bg_id', models.AutoField(primary_key=True, serialize=False)),
                ('bg_title', models.CharField(max_length=50)),
                ('bg_content', models.TextField()),
                ('bg_rentalFee', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('bg_startRentalDate', models.DateField(verbose_name='date published')),
                ('bg_endRentalDate', models.DateField(verbose_name='date published')),
                ('bg_reportingTime', models.DateField(verbose_name='date published')),
                ('bg_request', models.BooleanField()),
                ('bg_views', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BG_COMMENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_comment_datetime', models.DateTimeField(verbose_name='date published')),
                ('bg_comment_content', models.TextField()),
                ('bg_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bg_app.bg_item')),
            ],
        ),
        migrations.CreateModel(
            name='BG_BOARD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bg_app.bg_item')),
            ],
        ),
    ]
