# Generated by Django 3.1.1 on 2020-09-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bilyeoapp', '0001_initial'),
        ('bg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bg_item',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilyeoapp.user'),
        ),
        migrations.AddField(
            model_name='bg_comment',
            name='bg_comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bg_app.bg_item'),
        ),
        migrations.AddField(
            model_name='bg_board',
            name='bg_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bg_app.bg_item'),
        ),
    ]
