# Generated by Django 3.1 on 2020-09-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bg_item',
            name='bg_endRentalDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bg_item',
            name='bg_reportingTime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bg_item',
            name='bg_startRentalDate',
            field=models.DateField(),
        ),
    ]
