# Generated by Django 3.1 on 2020-09-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bg_app', '0002_auto_20200925_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bg_comment',
            name='bg_comment_datetime',
            field=models.DateTimeField(),
        ),
    ]
