# Generated by Django 3.1 on 2020-09-25 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BJ_ITEM',
            fields=[
                ('bj_id', models.AutoField(primary_key=True, serialize=False)),
                ('bj_title', models.CharField(max_length=50)),
                ('bj_content', models.TextField()),
                ('bj_reportingTime', models.DateField(verbose_name='date published')),
                ('bj_views', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BJ_COMMENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bj_comment_datetime', models.DateTimeField(verbose_name='date published')),
                ('bj_comment_content', models.TextField()),
                ('bj_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bj_app.bj_item')),
            ],
        ),
        migrations.CreateModel(
            name='BJ_BOARD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bj_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bj_app.bj_item')),
            ],
        ),
    ]
