# Generated by Django 3.1.1 on 2020-09-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bilyeoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BJ_ITEM',
            fields=[
                ('bj_id', models.AutoField(primary_key=True, serialize=False)),
                ('bj_title', models.CharField(max_length=50)),
                ('bj_content', models.TextField()),
                ('bj_views', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilyeoapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='BJ_COMMENT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bj_comment_datetime', models.DateTimeField(verbose_name='date published')),
                ('bj_comment_content', models.TextField()),
                ('bj_comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bj_app.bj_item')),
            ],
        ),
        migrations.CreateModel(
            name='BJ_BOARD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bj_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bj_app.bj_item')),
            ],
        ),
    ]
